spring:
  datasource:
    url: jdbc:mysql://192.168.0.100:3306/project1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 4444
mybatis-plus:
  mapper-locations: classpath*:StudentMapper.xml