apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubesphere
    component: score
    tier: backend
  name: score
  namespace: score-project
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: kubesphere
      component: score
      tier: backend
  template:
    metadata:
      labels:
        app: kubesphere
        component: score
        tier: backend
    spec:
      containers:
        - image: $DOCKERHUB_NAMESPACE/score:latest
          imagePullPolicy: Always
          name: score
          ports:
            - containerPort: 8106
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30